services:
  - type: web
    name: fincast-yfinance-api
    env: python
    rootDir: python_service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free

